In [ ]:
pip install https://github.com/pybrain/pybrain/archive/0.3.3.zip

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Using cached https://github.com/pybrain/pybrain/archive/0.3.3.zip
  Preparing metadata (setup.py) ... done


In [ ]:
from pybrain.structure import FeedForwardNetwork
from pybrain.structure import LinearLayer,SigmoidLayer, BiasUnit
from pybrain.structure import FullConnection 

rede = FeedForwardNetwork() # Conecta tudo 

camadaEntrada = LinearLayer(2) #entradas 
camadaOculta = SigmoidLayer(3) # Oculta 
camadaSaida = SigmoidLayer(1) # Saida

bias1 = BiasUnit()

bias2 = BiasUnit()

rede.addModule(camadaEntrada)
rede.addModule(camadaOculta)
rede.addModule(camadaSaida)
rede.addModule(bias1)
rede.addModule(bias2)

entradaOculta = FullConnection(camadaEntrada, camadaOculta)
ocultaSaida = FullConnection(camadaOculta, camadaSaida)
biasOculta = FullConnection(bias1, camadaOculta)
biasSaida = FullConnection(bias2, camadaSaida)

rede.sortModules()

print(rede) # Mostra a rede 
print(entradaOculta.params) # Mostra os pesos da camada oculta 
print(ocultaSaida.params)
print(biasOculta.params)
print(biasSaida.params)

FeedForwardNetwork-76
   Modules:
    [<BiasUnit 'BiasUnit-73'>, <BiasUnit 'BiasUnit-74'>, <LinearLayer 'LinearLayer-71'>, <SigmoidLayer 'SigmoidLayer-72'>, <SigmoidLayer 'SigmoidLayer-75'>]
   Connections:
    []

[-0.18999925 -0.91154148 -1.0311857  -0.02075265 -0.30226975  0.38313546]
[ 0.12163055 -0.12315314 -0.80572474]
[-0.05320515 -1.17091655 -0.12060243]
[0.03091093]


In [ ]:
# Pybrain fazedno o Xor 


from pybrain.tools.shortcuts import buildNetwork
from pybrain.datasets import SupervisedDataSet 
from pybrain.supervised.trainers import BackpropTrainer
from pybrain.structure.modules import SoftmaxLayer
from pybrain.structure.modules import SigmoidLayer



# Para tirar o bias basta fazer 
#rede = buildNetwork(2,3,1, outclass = SoftmaxLayer, hiddenclass = SigmoidLayer, bias = false) 
print(rede['in'])
print(rede['hidden0'])
print(rede['out'])
print(['bias'])

rede = buildNetwork(2,3,1)
base = SupervisedDataSet(2,1)
base.addSample((0,0), (0, ))
base.addSample((0,1),(1, ))
base.addSample((1,0), (1, ))

base.addSample((1,1), (0, ))

treinamento = BackpropTrainer(rede, dataset = base, learningrate=0.01,
                              momentum = 0.06)

for i in range (1,30000):
  erro = treinamento.train()
  if i % 1000 == 0:
    print("Erro : %s" %erro)


print(rede.activate([0,0]))

print(rede.activate([1,0]))

print(rede.activate([0,1]))

print(rede.activate([1,1]))


<LinearLayer 'in'>
<SigmoidLayer 'hidden0'>
<LinearLayer 'out'>
['bias']
Erro : 0.12811301204809408
Erro : 0.1262680690813363
Erro : 0.1235779469132902
Erro : 0.11792749865987877
Erro : 0.10925310708452982
Erro : 0.10409878330070163
Erro : 0.10025018508525659
Erro : 0.09675757446378132
Erro : 0.0927605573850413
Erro : 0.083593685734419
Erro : 0.04483478512834495
Erro : 0.006200405906516321
Erro : 0.00036693823939269537
Erro : 1.6893830508898905e-05
Erro : 7.372756749481242e-07
Erro : 3.1801723591003955e-08
Erro : 1.3687665933227055e-09
Erro : 5.902023293432744e-11
Erro : 2.5497874085605825e-12
Erro : 1.1006072335309133e-13
Erro : 4.779385315215815e-15
Erro : 2.0781833610162916e-16
Erro : 9.050354697186974e-18
Erro : 3.963635896758948e-19
Erro : 1.7374654433732986e-20
Erro : 7.655553418557179e-22
Erro : 3.387402615682326e-23
Erro : 1.496063727410222e-24
Erro : 6.781866014097007e-26
[-6.66133815e-16]
[1.]
[1.]
[1.3500312e-13]


In [ ]:
from sklearn.utils.fixes import sklearn
# Scikit - learn e Iris dataset 

from sklearn.neural_network import MLPClassifier

from sklearn import datasets 

iris = datasets.load_iris()

entradas = iris.data
saidas = iris.target 
redeNeural = MLPClassifier(verbose = True, 
                           max_iter =1000,
                           tol = 0.00001,
                           activation = 'logistic')# loss esta em loss

redeNeural.fit(entradas,saidas)




Iteration 1, loss = 1.15166667
Iteration 2, loss = 1.13449871
Iteration 3, loss = 1.12072064
Iteration 4, loss = 1.11016530
Iteration 5, loss = 1.10248371
Iteration 6, loss = 1.09711113
Iteration 7, loss = 1.09332985
Iteration 8, loss = 1.09041044
Iteration 9, loss = 1.08775296
Iteration 10, loss = 1.08495627
Iteration 11, loss = 1.08181058
Iteration 12, loss = 1.07825197
Iteration 13, loss = 1.07431172
Iteration 14, loss = 1.07007429
Iteration 15, loss = 1.06564603
Iteration 16, loss = 1.06113324
Iteration 17, loss = 1.05662770
Iteration 18, loss = 1.05219820
Iteration 19, loss = 1.04788709
Iteration 20, loss = 1.04371088
Iteration 21, loss = 1.03966379
Iteration 22, loss = 1.03572326
Iteration 23, loss = 1.03185621
Iteration 24, loss = 1.02802549
Iteration 25, loss = 1.02419550
Iteration 26, loss = 1.02033648
Iteration 27, loss = 1.01642706
Iteration 28, loss = 1.01245509
Iteration 29, loss = 1.00841695
Iteration 30, loss = 1.00431615
Iteration 31, loss = 1.00016154
Iteration 32, los

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


array([0])

In [ ]:
from numpy import array
redeNeural.predict([[5,7.2,5.1,2.2]])


array([0])